### ISSUE TITLE
API is misleading and can lead to security issues

### ISSUE THREAD

**Issue by thotypous** [spisemisu/elm-sha#3]
First of all, thanks for this library. It is great to see you care about testing it to ensure correctness and to handle UTF-8 correctly.

However, there is a major issue with the API design. Handling every string beginning with "0x" as an hex string causes two problems:

* **Compatibility**: Now you have lost compatibility with other SHA implementations. Let's say I want to take a string `s` obtained from user input and compute its sha256sum, by calling `sha256sum s`. Now let's say `s="0x20"`. I will get `36a9e7f1c95b82ffb99743e0c5c4ce95d83c9a430aac59f84ef3cbfab6145068` with elm-sha, whereas other implementations will give `a766b7b336b982ec85609aa5fe6b51e33e87b879398183ae546a96138a61402a`.

* **Security**: Let's say I don't require compatibility with other SHA implementations: all I need is a cryptographically secure hash function. It's easy to see the `sha256sum` implemented by elm-sha is not collision-resistant: `sha256sum "0x:"` and `sha256sum "0xa"` result in the same hash (`01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b`). Even if you modify your `isHex` function to check whether the input matches the regex `0x[0-9a-f]+`, you still wouldn't get collision-resistance. By construction, you would always be able to collide `sha256sum " "` with `sha256sum "0x20"`.

That without citing version breakage: `elm-sha>=1.0.4` is not API-compatible with `elm-sha<=1.0.3`, as would be required by Elm version conventions (API should be compatible between minor releases).

Currently, there are two ways to mitigate the compatibility and security issues:

* Disallow strings beginning with "0x": consider them as invalid input. This is not always possible to do. Sometimes you want to be able to accept strings beginning with "0x" from your user.

* Handle the Unicode to UTF-8 conversion yourself, then convert your string to hex and prepend "0x". This needlessly increases the complexity of the code, forcing the user to reimplement part of the code which is already implemented by the library. It also wastes some computational resources (data is converted to a byte array, then to hex, then back to a byte array).

Therefore, the I propose the API to be redesigned in some way such the input to a function is always treated either as unicode or as hex. For example, the following API could be an option, and it preserves compatibility with the API from `elm-sha<=1.0.3`:

```elm
sha256bytes : ByteArray -> String

utf8encode: String -> ByteArray

hex2bytes : String -> ByteArray

sha256sum : String -> String
sha256sum = utf8encode >> sha256bytes
```

where `ByteArray` could be e.g. `Array Int` or `Array Char`.

Then the unit tests could use `hex2bytes >> sha256bytes` instead of `sha256sum`.

**Comment by gentauro** [comment]
Hi @thotypous.

Thank you for your issue. It has some reasonable and valid points.

Here are a few comments:

- With regard of the `ByteArray` I would probably have done it that way if there was a `Byte` type in Elm.

- The issues I found, and have pointed out in other on other issues, is that I can't have an assumption of what a string is in `JavaScript` and hereby `Elm`.

But it's a long time ago since I `ported` this functionality to `Elm` so I really don't remember the implementation issues I faced.

That said, I would be open for a re-design, if what is presented is working, as I might have taken a `shortcut` to handle the first and only `NIST test case` that failed ...

Would you be willing to provide a `pull` request with your suggestions?

**Comment by thotypous** [comment]
Hi, thank you for your prompt response. I can try to put together a pull request, but it will take 2 or 3 weeks until I have the time to touch this again.

**Comment by gentauro** [comment]
Hi @thotypous.

I finally had some time to look into this issue. I have created the following `Bytes` type in order to handle `bytes` in Elm:

- http://package.elm-lang.org/packages/spisemisu/elm-bytes/1.0.0/Bytes

I had some initial implementation but got dismissed due to excessive memory overhead, got help from `#elm-dev` at slack, mostly eeue56

- First version (dismissed due to twice size for every byte):

```elm
type BytePrime = B {- Don't expose B from module to ensure valid 0 - 255 values -} Int

zero : BytePrime
zero =
  B 000

b : Int -> Result String BytePrime
b number =
  case number >= 0 && number <= 255 of
    True  -> B number |> Ok
    False -> Err <| "Number (" ++ (toString number) ++ ") is not a byte. Must be in range 0 - 255."

toIntPrime : BytePrime -> Int
toIntPrime (B number) =
number
```

- Second version (dismissed due to lack of performance due to big `case ... of`:

```elm
type Byte
  = B000 | B032 | B064 | B096 | B128 | B160 | B192 | B224
  | B001 | B033 | B065 | B097 | B129 | B161 | B193 | B225
  | B002 | B034 | B066 | B098 | B130 | B162 | B194 | B226
  ...
  | B031 | B063 | B095 | B127 | B159 | B191 | B223 | B255

toInt : Byte -> Result String Int
toInt byte =
  byte |> toString |> String.dropLeft 1 |> String.toInt

fromInt : Int -> Result String Byte
fromInt number =
  case number of
    000 -> Ok B000
    001 -> Ok B001
    002 -> Ok B002
    ...
    255 -> Ok B255
any -> Err <| "Number (" ++ (toString any) ++ ") is not a byte. Must be in range 0 - 255."
```

I'll very shortly replace the `elm-utf8` with `elm-bytes` in `elm-sha`. Stay tuned :+1:

**Comment by gentauro** [comment]
Hi @thotypous 

It's done:

- http://package.elm-lang.org/packages/spisemisu/elm-sha/1.1.0

I'm closing this issue. Please re-open if you disagree with the provided solution.

/CC @icidasset please look into how this issue is solved as it definitely is going to have an impact on your code (`elm-package bump` decided it was a `MINOR` change so you will actually get this package if you just re-download packages). I thought about re-naming _*something*_ but it really doesn't give any sense. So even though package `semantics` are forced technically by code, it doesn't solve `semantics` that doesn't change `signatures`, sadly:

- https://github.com/spisemisu/elm-sha/issues/2

**Comment by icidasset** [comment]
@gentauro Thanks for the heads up! 😄

**Comment by thotypous** [comment]
The new API looks pretty fine. Thanks very much @gentauro
